notifications:
  email: false

git:
  depth: 2

# sudo: false

language: node_js

node_js:
  - iojs
  - 0.10.36

install:
  - npm install
  - curl https://install.meteor.com | /bin/sh
  - meteor --version
  - phantomjs -v

script:
  # - make test.coverage.coveralls
  - make test.meteor.headless